/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.binchoo.movie;

import org.binchoo.movie.discount.condition.DiscountCondition;
import org.binchoo.movie.discount.policy.AbstractDiscountPolicy;

public class MovieClient {

    public static void main(String[] args) {
        System.out.println("Hello, I'm movie client!");

        DiscountCondition fooDiscountCondition = new DiscountCondition() {
            @Override
            public boolean isSatisfied() {
                return true;
            }

            @Override
            public String toString() {
                return "Hello, I'm fooDiscountCondition!";
            }
        };

        AbstractDiscountPolicy fooDiscountPolicy = new AbstractDiscountPolicy(fooDiscountCondition) {
            @Override
            protected int getDiscountAmount() {
                return 0;
            }
        };

        Movie m = new Movie("Ironman", fooDiscountPolicy);

        System.out.println(m);
    }
}
