/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.binchoo.movie;

import org.binchoo.movie.discount.policy.AbstractDiscountPolicy;

public class Movie {

    private String name;
    private AbstractDiscountPolicy discountPolicy;

    public Movie(String name, AbstractDiscountPolicy discountPolicy) {
        this.name = name;
        this.discountPolicy = discountPolicy;
    }

    public String getName() {
        return name;
    }

    public AbstractDiscountPolicy getDiscountPolicy() {
        return discountPolicy;
    }

    @Override
    public String toString() {
        return "Movie{" +
                "name='" + name + '\'' +
                ", discountPolicy=" + discountPolicy +
                '}';
    }
}
