/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.binchoo.movie;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MovieClientTest {
    @Test void appHasAGreeting() {
    }
}
